-- Inserts for Dim_Department
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP01', 'Dept- Cardiology', 'Internal Medicine', 'Cardiology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP02', 'Dept- Neurology', 'Internal Medicine', 'Neurology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP03', 'Dept- Orthopedics', 'Surgical Specialties', 'Orthopedics', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP04', 'Dept- Oncology', 'Diagnostic & Cancer Care', 'Oncology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP05', 'Dept- Pediatrics', 'Primary & Preventive Care', 'Pediatrics', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP06', 'Dept- Dermatology', 'Specialty Care', 'Dermatology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP07', 'Dept- Ophthalmology', 'Specialty Care', 'Ophthalmology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP08', 'Dept- Otolaryngology', 'Specialty Care', 'Otolaryngology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP09', 'Dept- General Surgery', 'Surgical Specialties', 'General Surgery', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP10', 'Dept- Plastic Surgery', 'Surgical Specialties', 'Plastic Surgery', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP11', 'Dept- Endocrinology', 'Internal Medicine', 'Endocrinology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP12', 'Dept- Rheumatology', 'Internal Medicine', 'Rheumatology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP13', 'Dept- Nephrology', 'Internal Medicine', 'Nephrology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP14', 'Dept- Urology', 'Surgical Specialties', 'Urology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP15', 'Dept- Pulmonology', 'Internal Medicine', 'Pulmonology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP16', 'Dept- Gastroenterology', 'Internal Medicine', 'Gastroenterology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP17', 'Dept- Hematology', 'Internal Medicine', 'Hematology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP18', 'Dept- Obstetrics and Gynecology', 'Surgical Specialties', 'Obstetrics and Gynecology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP19', 'Dept- Infectious Diseases', 'Internal Medicine', 'Infectious Diseases', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP20', 'Dept- Emergency Medicine', 'Emergency & Support Services', 'Emergency Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP21', 'Dept- Anesthesiology', 'Emergency & Support Services', 'Anesthesiology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP22', 'Dept- Pathology', 'Diagnostic & Cancer Care', 'Pathology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP23', 'Dept- Radiology', 'Diagnostic & Cancer Care', 'Radiology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP24', 'Dept- Nuclear Medicine', 'Diagnostic & Cancer Care', 'Nuclear Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP25', 'Dept- Pain Management', 'Surgical Specialties', 'Pain Management', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP26', 'Dept- Allergy and Immunology', 'Internal Medicine', 'Allergy and Immunology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP27', 'Dept- Rehabilitation Medicine', 'Emergency & Support Services', 'Rehabilitation Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP28', 'Dept- Geriatrics', 'Primary & Preventive Care', 'Geriatrics', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP29', 'Dept- Clinical Pharmacology', 'Emergency & Support Services', 'Clinical Pharmacology', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP30', 'Dept- Family Medicine', 'Primary & Preventive Care', 'Family Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP31', 'Dept- Sports Medicine', 'Surgical Specialties', 'Sports Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP32', 'Dept- Sleep Medicine', 'Primary & Preventive Care', 'Sleep Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP33', 'Dept- Occupational Medicine', 'Primary & Preventive Care', 'Occupational Medicine', 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP34', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP35', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP36', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP37', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP38', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP39', 'Dept- ', NULL, NULL, 'yet to fill');
INSERT INTO Dim_Department (DepartmentID, DepartmentName, DepartmentCategory, Specialization, HOD) VALUES ('DEP40', 'Dept- ', NULL, NULL, 'yet to fill');

-- Inserts for Dim_Diagnosis
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX01', 'Hypertension');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX02', 'Type 2 Diabetes Mellitus');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX03', 'Acute Bronchitis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX04', 'Pneumonia');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX05', 'Chronic Obstructive Pulmonary Disease (COPD)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX06', 'Coronary Artery Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX07', 'Heart Failure');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX08', 'Stroke (Cerebrovascular Accident)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX09', 'Atrial Fibrillation');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX10', 'Gastroesophageal Reflux Disease (GERD)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX11', 'Peptic Ulcer Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX12', 'Chronic Kidney Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX13', 'Urolithiasis (Kidney Stones)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX14', 'Hypothyroidism');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX15', 'Hyperthyroidism');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX16', 'Osteoarthritis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX17', 'Rheumatoid Arthritis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX18', 'Depression');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX19', 'Anxiety Disorder');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX20', 'Migraine');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX21', 'Seizure Disorder / Epilepsy');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX22', 'Acute Appendicitis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX23', 'Gallstones (Cholelithiasis)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX24', 'Anemia');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX25', 'Infectious Diarrhea');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX26', 'Cellulitis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX27', 'Dermatitis / Eczema');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX28', 'Fracture - Wrist');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX29', 'Fracture - Hip');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX30', 'Back Pain (Low Back Pain)');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX31', 'Parkinson’s Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX32', 'Alzheimer’s Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX33', 'Chronic Liver Disease');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX34', 'Alcohol Use Disorder');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX35', 'Pneumothorax');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX36', 'Sepsis');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX37', 'Acute Kidney Injury');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX38', 'Obsessive Compulsive Disorder');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX39', 'Chronic Fatigue Syndrome');
INSERT INTO Dim_Diagnosis (DiagnosisID, DiagnosisName) VALUES ('DX40', 'Allergic Rhinitis');

-- Inserts for Dim_Treatment
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR01', 'ECG');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR02', 'Blood Sugar Test');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR03', 'MRI Scan');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR04', 'CT Scan');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR05', 'X-Ray');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR06', 'Ultrasound');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR07', 'Physical Therapy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR08', 'Chemotherapy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR09', 'Radiation Therapy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR10', 'Cardiac Catheterization');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR11', 'Angioplasty');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR12', 'Joint Replacement Surgery');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR13', 'Knee Arthroscopy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR14', 'Appendectomy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR15', 'Liver Function Test');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR16', 'Dialysis');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR17', 'Stress Test');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR18', 'Endoscopy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR19', 'Colonoscopy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR20', 'Psychiatric Counseling');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR21', 'Antibiotic Treatment');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR22', 'Blood Transfusion');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR23', 'Hypertension Medication');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR24', 'Insulin Therapy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR25', 'Wound Dressing');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR26', 'Intensive Care Monitoring');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR27', 'Sleep Study');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR28', 'Occupational Therapy');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR29', 'Vaccination');
INSERT INTO Dim_Treatment (TreatmentID, TreatmentName) VALUES ('TR30', 'Pain Management Injection');

-- Inserts for Dim_PaymentMethod
INSERT INTO Dim_PaymentMethod (PaymentMethodID, PaymentMethod) VALUES ('PM01', 'Cash');
INSERT INTO Dim_PaymentMethod (PaymentMethodID, PaymentMethod) VALUES ('PM02', 'Debit Card');
INSERT INTO Dim_PaymentMethod (PaymentMethodID, PaymentMethod) VALUES ('PM03', 'Credit Card');
INSERT INTO Dim_PaymentMethod (PaymentMethodID, PaymentMethod) VALUES ('PM04', 'UPI');
